import { ForumProvider } from "@/context/forum.context";
import "../styles/globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/layouts/navbar";
import { CommentProvider } from "@/context/comment.context";
import { AuthProvider } from "@/context/auth.context";
import ProtectedRoute from "@/components/protected-route";
import { ProfileProvider } from "@/context/profile.context";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ProtectedRoute>
            <ForumProvider>
              <Navbar />
              <CommentProvider>
                <ProfileProvider>{children}</ProfileProvider>
              </CommentProvider>
            </ForumProvider>
          </ProtectedRoute>
        </AuthProvider>
      </body>
    </html>
  );
}
